import { Map } from "immutable";

export const CURRENT_PLAYERS_ACTIONS = Map({
  ADD_CURRENT_PLAYER: "ADD_CURRENT_PLAYER",
  REMOVE_CURRENT_PLAYER: "REMOVE_CURRENT_PLAYER",
  CLEAR_CURRENT_PLAYER_ERROR: "CLEAR_CURRENT_PLAYERS_ERROR"
});

export default CURRENT_PLAYERS_ACTIONS;
